const mockCaninos = [
  {
    id: 1,
    nombre: "Max",
    raza: "Golden Retriever",
    edad: "3 años",
    tamaño: "grande",
    dueño_id: 1,
    plan_id: 1,
    notas: "Muy sociable, le encanta jugar con otros perros",
    fecha_registro: "2024-01-15",
    foto: "https://images.pexels.com/photos/1805164/pexels-photo-1805164.jpeg?auto=compress&cs=tinysrgb&w=300",
  },
  {
    id: 2,
    nombre: "Luna",
    raza: "Border Collie",
    edad: "2 años",
    tamaño: "mediano",
    dueño_id: 1,
    plan_id: 2,
    notas: "Muy inteligente, necesita estimulación mental",
    fecha_registro: "2024-02-20",
    foto: "https://images.pexels.com/photos/551628/pexels-photo-551628.jpeg?auto=compress&cs=tinysrgb&w=300",
  },
  {
    id: 3,
    nombre: "Coco",
    raza: "French Bulldog",
    edad: "1 año",
    tamaño: "pequeño",
    dueño_id: 1,
    plan_id: 3,
    notas: "Tranquilo, ideal para apartamento",
    fecha_registro: "2024-03-10",
    foto: "https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?auto=compress&cs=tinysrgb&w=300",
  },
];

const mockMatriculas = [
  {
    id: 1,
    canino_id: 1,
    plan: "6m",
    transporte: "completo",
    fecha_inicio: "2024-01-15",
    fecha_fin: "2024-07-15",
    estado: "activa",
  },
  {
    id: 2,
    canino_id: 2,
    plan: "3m",
    transporte: "mañana",
    fecha_inicio: "2024-02-20",
    fecha_fin: "2024-05-20",
    estado: "próxima a vencer",
  },
  {
    id: 3,
    canino_id: 3,
    plan: "1m",
    transporte: "ninguno",
    fecha_inicio: "2024-02-10",
    fecha_fin: "2024-03-10",
    estado: "vencida",
  },
];

const mockAsistencias = [
  {
    id: 1,
    canino_id: 1,
    fecha: "2024-03-16",
    via_ruta: true,
    ruta: "mañana",
    hora_llegada: "08:30",
    hora_salida: "17:00",
    despacho_por_ruta: true,
  },
  {
    id: 2,
    canino_id: 1,
    fecha: "2024-03-17",
    via_ruta: true,
    ruta: "mañana",
    hora_llegada: "08:45",
    hora_salida: "17:15",
    despacho_por_ruta: true,
  },
  {
    id: 3,
    canino_id: 2,
    fecha: "2024-03-21",
    via_ruta: true,
    ruta: "mañana",
    hora_llegada: "08:20",
    hora_salida: "13:00",
    despacho_por_ruta: false,
  },
  {
    id: 4,
    canino_id: 1,
    fecha: "2024-03-18",
    via_ruta: false,
    ruta: "ninguna",
    hora_llegada: "09:00",
    hora_salida: "16:30",
    despacho_por_ruta: false,
  },
  {
    id: 5,
    canino_id: 3,
    fecha: "2024-03-11",
    via_ruta: false,
    ruta: "ninguna",
    hora_llegada: "10:00",
    hora_salida: "15:00",
    despacho_por_ruta: false,
  },
  {
    id: 6,
    canino_id: 3,
    fecha: "2024-03-11",
    via_ruta: false,
    ruta: "ninguna",
    hora_llegada: "10:00",
    hora_salida: "15:00",
    despacho_por_ruta: false,
  },
];

const mock = {
  internalUsers: [
    {
      id: "u1",
      name: "Ana Gómez",
      email: "ana@admin.com",
      role: "admin",
      active: true,
    },
    {
      id: "u2",
      name: "Carlos Ruiz",
      email: "carlos@director.com",
      role: "director",
      active: true,
    },
  ],
  clients: [
    {
      id: "c1",
      name: "Laura Torres",
      email: "laura@example.com",
      phone: "3105551111",
      address: "Calle 123 #45-67",
      dogs: ["d1", "d2"],
    },
    {
      id: "c2",
      name: "Pedro López",
      email: "pedro@example.com",
      phone: "3115552222",
      address: "Carrera 9 #80-10",
      dogs: ["d3"],
    },
  ],
  dogs: [
    {
      id: "d1",
      ownerId: "c1",
      name: "Max",
      breed: "Labrador",
      ageMonths: 36,
      size: "grande",
      notes: "Muy juguetón",
      enrollments: ["e1"],
    },
    {
      id: "d2",
      ownerId: "c1",
      name: "Luna",
      breed: "Poodle",
      ageMonths: 12,
      size: "pequeño",
      notes: "Un poco tímida",
      enrollments: ["e2"],
    },
    {
      id: "d3",
      ownerId: "c2",
      name: "Rocky",
      breed: "Bulldog",
      ageMonths: 48,
      size: "mediano",
      notes: "Problemas de respiración",
      enrollments: ["e3"],
    },
  ],
  enrollments: [
    {
      id: "e1",
      dogId: "d1",
      plan: "6m",
      transport: "mañana",
      startDate: "2025-08-01",
      endDate: "2026-02-01",
      status: "activa",
    },
    {
      id: "e2",
      dogId: "d2",
      plan: "3m",
      transport: "ninguno",
      startDate: "2025-09-01",
      endDate: "2025-12-01",
      status: "activa",
    },
    {
      id: "e3",
      dogId: "d3",
      plan: "1m",
      transport: "tarde",
      startDate: "2025-10-01",
      endDate: "2025-11-01",
      status: "pendiente",
    },
  ],
  attendances: [
    {
      id: "a1",
      dogId: "d1",
      date: "2025-10-02",
      viaRoute: true,
      route: "Ruta Mañana",
      arrivalTime: "08:20",
      departureTime: "17:00",
      recordedBy: "u2",
    },
    {
      id: "a2",
      dogId: "d2",
      date: "2025-10-02",
      viaRoute: false,
      arrivalTime: "09:00",
      departureTime: "16:30",
      recordedBy: "u2",
    },
    {
      id: "a3",
      dogId: "d3",
      date: "2025-10-02",
      viaRoute: true,
      route: "Ruta Tarde",
      arrivalTime: "14:00",
      departureTime: "18:00",
      recordedBy: "u1",
    },
  ],
};
export { mockCaninos, mockMatriculas, mockAsistencias, mock };
